"""add_email_status_to_leads

Revision ID: 33fcb7868b87
Revises: 0001
Create Date: 2026-03-20 22:59:21.035928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33fcb7868b87'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    All operations are guarded with try/except because init_db()/create_all()
    may have already created these columns and indexes before Alembic ran.
    """
    for col in [
        sa.Column('email_status', sa.String(length=50), nullable=True),
        sa.Column('last_verified', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    ]:
        try:
            op.add_column('leads', col)
        except Exception:
            pass
    try:
        op.create_index('ix_leads_email_fund', 'leads', ['email', 'fund'], unique=True)
    except Exception:
        pass
    try:
        op.create_index('ix_leads_name_fund', 'leads', ['name', 'fund'], unique=False)
    except Exception:
        pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leads_name_fund', table_name='leads')
    op.drop_index('ix_leads_email_fund', table_name='leads')
    op.drop_column('leads', 'last_crawled_at')
    op.drop_column('leads', 'last_verified')
    op.drop_column('leads', 'email_status')
    # ### end Alembic commands ###
